resources:
  - name: git-repo
    type: git
    icon: github-circle
    source:
      uri: https://github.com/Nova-472/LocationBasedTime

jobs:
  - name: build
    public: true
    plan:
      - get: git-repo
        trigger: true
      - task:
          config:
            inputs:
              - name: git-repo
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: openjdk
                tag: 8-jdk
            caches:
              - path: ./gradle
            run:
              path: bash
              args: ["build.sh"]